_wandb:
    value:
        cli_version: 0.23.1
        e:
            78hk2ou3l8r5d1rzlcm42yo2jgovrm02:
                args:
                    - /mnt/data/syl-gpt-refactor/Configs/trained_eng_bpe_config.json
                    - /mnt/data/syl-gpt-refactor/Data/english_data/bins
                    - /mnt/data/weights/finetuned
                    - --weights_path
                    - /mnt/data/weights/old_goods/eng_bpe_good.pth
                    - --task
                    - word
                    - --cross_val_counter
                    - "0"
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "155897610240"
                        used: "95149953024"
                email: tiyliu@ucdavis.edu
                executable: /mnt/data/syl-gpt-refactor/Training/.venv/bin/python3
                git:
                    commit: 12d8425b098fe4afe2d9fa1fecdd63a56183fa8d
                    remote: https://github.com/timo-liu/syl-gpt-refactor.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-be6cc75b-e0d8-1a02-94bc-390ddd945f7d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6e16cf67-1d39-83d9-ad9d-de4bf2c53568
                host: A100
                memory:
                    total: "464879476736"
                os: Linux-6.8.0-1044-azure-x86_64-with-glibc2.35
                program: -m Training.train
                python: CPython 3.10.11
                root: /mnt/data/syl-gpt-refactor
                startedAt: "2025-12-31T14:31:08.893418Z"
                writerId: 78hk2ou3l8r5d1rzlcm42yo2jgovrm02
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 61
            "4": 3.10.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
