_wandb:
    value:
        cli_version: 0.23.1
        e:
            egxao8zsl4gr57kfp95e1ztu8l4hth77:
                args:
                    - /mnt/data/syl-gpt-refactor/Configs/trained_eng_bpe_config.json
                    - /mnt/data/syl-gpt-refactor/Data/english_data/bins
                    - /mnt/data/weights/finetuned
                    - --weights_path
                    - /mnt/data/weights/old_goods/eng_bpe_good.pth
                    - --task
                    - g2p
                    - --cross_val_counter
                    - "6"
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "155897610240"
                        used: "95132098560"
                email: tiyliu@ucdavis.edu
                executable: /mnt/data/syl-gpt-refactor/Training/.venv/bin/python3
                git:
                    commit: 5faa3b4baf7e8dec88537c033a15d5f8161943f8
                    remote: https://github.com/timo-liu/syl-gpt-refactor.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-28c511ab-feec-0b9a-1889-98ef06ace9dc
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6b9c42cc-4a61-70a6-4fae-b8ca2c84d879
                host: A100
                memory:
                    total: "464879476736"
                os: Linux-6.8.0-1044-azure-x86_64-with-glibc2.35
                program: -m Training.train
                python: CPython 3.10.11
                root: /mnt/data/syl-gpt-refactor
                startedAt: "2025-12-28T19:29:16.447603Z"
                writerId: egxao8zsl4gr57kfp95e1ztu8l4hth77
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 61
            "4": 3.10.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
