_wandb:
    value:
        cli_version: 0.23.1
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
            "3":
                - 13
            "4": 3.10.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
